### ISSUE TITLE
Game crashes when entering the end

### ISSUE THREAD

**Issue by DanexaPlay** [fudgeu/playlist#10]
![image](https://user-images.githubusercontent.com/90069570/181459640-75a66578-4ea1-49b7-aa5e-941a8a523ab1.png)
crash report - [crash-2022-07-28_11.30.05-client.txt](https://github.com/fudgeu/playlist/files/9207207/crash-2022-07-28_11.30.05-client.txt)

**Comment by itzme1on** [comment]
Вот если автор загрузит сюда исходный код плагина, то я рад заняться его разработкой, но автор пока не выходит на связь

**Comment by itzme1on** [comment]
> Вот если автор загрузит сюда исходный код плагина, то я рад заняться его разработкой, но автор пока не выходит на связь 

А нет. Автор написал, что выложит код как только почистит код и выпустит более-менее стабильную версию мода. Тогда ждём

**Comment by fudgeu** [comment]
Sorry for the late reply, I've been on vacation and school had also started. Can you please attach an archive of the 'playlist' folder in your Minecraft root folder? And if possible, which playlist was playing when this happened? Thank you!

**Comment by DanexaPlay** [comment]
> Sorry for the late reply, I've been on vacation and school had also started. Can you please attach an archive of the 'playlist' folder in your Minecraft root folder? And if possible, which playlist was playing when this happened? Thank you!

Sorry that i didnt answer you before, i use github quite rare.
This is an archive of my playlist folder
[playlist.zip](https://github.com/fudgeu/playlist/files/9725319/playlist.zip)
I think that its crashes with standart playlist, i can't be completely sure

**Comment by fudgeu** [comment]
Thank you! I'll take a look at it soon
