### ISSUE TITLE
Context menu goes off-screen.

### ISSUE THREAD

**Issue by T3RRY4** [fudgeu/playlist#13]
When right-clicking on a track at the bottom of a playlist, the context menu goes off-screen.

![image](https://user-images.githubusercontent.com/35370166/183160644-88fc82b6-985a-4a88-99cf-a2aa5bd3c181.png)

**Comment by fudgeu** [comment]
Fixed, expect it in the next update!
(Sorry for the hiatus, I just returned from vacation and pretty much started schooling right away so its been hectic)
