### ISSUE TITLE
1.19.1 Version

### ISSUE THREAD

**Issue by ComradeBlaze** [fudgeu/playlist#19]
Hi, sorry if I'm uninformed but could a 1.19.1 version be published? At the moment there's only a 1.19 and a 1.19.2 version and the 1.1.0 release does not work with 1.19.1. I don't know how to make mods run on different versions so I'd really appreciate it. Thank you!

**Comment by fudgeu** [comment]
Hi! Sorry for the late reply - It doesn't take much so I might as well release a 1.19.1 version. I'm close to releasing the next update so I'll make sure to compile a 1.19.1 version of it as well!

**Comment by ComradeBlaze** [comment]
Thank you!
