### ISSUE TITLE
(Logo upgrade)  Updated logo art

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#21]
If you want too, you can use this updated art I made its small but a upgrade none a less

![playlist logo](https://user-images.githubusercontent.com/109874700/194458734-a61babd7-c0e1-4714-8da3-3060504faff2.png) <-- 8x10 verison

![Playlist art (Github)](https://user-images.githubusercontent.com/109874700/194458745-50848475-8a32-482e-9d33-c90c5e8bea2c.png)

If I need to fix anything tell me

**Comment by itzme1on** [comment]
really good

**Comment by DeadbushCarrot** [comment]
> 

thxs

**Comment by fudgeu** [comment]
Hi! It looks great - I'll include it in the next update (1.3.0), and I'll add your name to the credits somewhere lol
Thank you!
