### ISSUE TITLE
Can I configure the delay between Minecraft's in-game music with this mod, even if I just let MC automatically choose the song

### ISSUE THREAD

**Issue by TechPro424** [fudgeu/playlist#22]
Can I configure the delay between Minecraft's in-game music with this mod, even if I just let MC automatically choose the song like in Vanilla?
Basically, I use this mod: https://modrinth.com/mod/moremusic to reduce delay between MC music tracks
Can I do that with Playlist while retaining the rest of the Vanilla behavior? (that is, letting mc choose the music they way it would do without this mod)

**Comment by DeadbushCarrot** [comment]
I think you can change the delay in the playlist all ready I need to check

**Comment by fudgeu** [comment]
Correct, you can edit the default playlist (which contains all vanilla songs by default and will play them in the right context) to reduce or remove the timings

**Comment by DeadbushCarrot** [comment]
> 

btw right click on a playlist to change the timings

**Comment by TechPro424** [comment]
Thanks!
