### ISSUE TITLE
Make it so you can tell what loop setting you have selected!

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#23]
So basically i downloaded the new update and I see the loop button i press it until it a loop with 2 dot so i thought it was gunna loop the song but it didn't it took a few minutes to realize that the one with no 2 dot would loop it so if possible add text that hovers over the loop button that tells you what loop setting you selected!

**Comment by fudgeu** [comment]
Yup, will do! I was already planning on expanding the loop button with more options anyway and a new menu, so there will def be a clearer view soon

As it stands, the current ones are:
- The default play mode (condition-based)
- Repeat forever (the repeat symbol)
- Repeat once (the repeat symbol with what I tried to make look like a '1' in the top right corner, the two dots lol)

**Comment by DeadbushCarrot** [comment]
oh here I made the 2 dots look like a 1  
![repeat_once](https://user-images.githubusercontent.com/109874700/201224868-2c8136a4-dae5-47fd-9aa3-4b364b300121.png)
