### ISSUE TITLE
Playlists repeat for a long time?

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#26]
So basically I opened the playlist menu and i see the same 3 playlist repeating to the bottum of the menu Here a zip of my playlist
[playlist.zip](https://github.com/fudgeu/playlist/files/9998842/playlist.zip)

**Comment by fudgeu** [comment]
I likely have an idea of what is causing this, I'll let you know if it gets fixed!

**Comment by fudgeu** [comment]
Fixed in 1.2.1 releasing whenever it gets approved :)
