### ISSUE TITLE
Feature Suggestion - Music Control Hotkeys

### ISSUE THREAD

**Issue by ComradeBlaze** [fudgeu/playlist#27]
Would be useful to able to bind hotkeys to be able to skip/go back/pause music without having to open the menu. Not a very pressing issue but it would be amazing if possible :D Thanks, amazing mod!

**Comment by fudgeu** [comment]
Yup, expect it in 1.2.1! I don't know why I haven't added it earlier, I'm pretty sure it actually existed in the very early stages of the mod and somehow got removed lol
