### ISSUE TITLE
1.19.3 Version 

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#28]
Playlist doesn't have 1.19.3 support

**Comment by TechPro424** [comment]
Please update to 1.19.3 @fudgeu \

**Comment by DeadbushCarrot** [comment]
> Please update to 1.19.3 @fudgeu

I dont think he's gunna update it

**Comment by sternschnaube** [comment]
Hello, please give him time @DeadbushCarrot.
I'm pretty sure we will see the mod for 1.19.3 in the near future 😊

**Comment by fudgeu** [comment]
Hi all! Sorry for the hiatus, I've been really busy over this holiday break and have also been working on other projects. I was hoping to get 1.2.1 finished for 1.19.3, but seeing that I haven't had much time to work on it, I will likely release 1.2.0 for 1.19.3. I'm starting work on this mod again though, so 1.2.1 shouldn't be far off either!

**Comment by sternschnaube** [comment]
Great to hear - you have all the time, don't rush it please.
I will keep my eye on it 👍🏿

**Comment by TechPro424** [comment]
No issues, take your time and don't rush it! After all, everyone needs some
time off

**Comment by DeadbushCarrot** [comment]
True

**Comment by fudgeu** [comment]
So, taking a look into it, 1.19.3 has seemed to changed a lot of stuff, especially around playing sounds, UI, and resource loading, all things that this mod heavily relies on. I've already fixed some of the sound stuff, I think resource loading should be easy, and I'll just have to see how it goes with the UI stuff.

So, might take a bit longer than I hoped it would to update it to 1.19.3, but shouldn't be too much longer

**Comment by fudgeu** [comment]
Find 1.2.1 for 1.19.3 [here!](https://modrinth.com/mod/playlist/version/1.2.1)

**Comment by sternschnaube** [comment]
Thank you 😊
