### ISSUE TITLE
Backporting

### ISSUE THREAD

**Issue by Slips-PC** [fudgeu/playlist#30]
Hi - is there any chance of you backporting some of the fixes and additions from 1.2 onwards to a version of the mod for 1.19? I play on 1.19 since the server i play on is still on that version, and missing some of the extra additions and bugfixes (especially the whole "crashing when entering the end" issue) is really unfortunate.

**Comment by DeadbushCarrot** [comment]
Yeah this should be easy for him to do but he's working on the 1.3 update so maybe when that comes out

**Comment by fudgeu** [comment]
I'll look into it :)
Like Carrot said, shouldn't be too hard. I'm busy working on 1.3.0 (currently creating a whole UI library, so a lil' ambitious) but I can easily implement 1.2.1's features into 1.19 quickly maybe expect to see something in the next day or two!

**Comment by fudgeu** [comment]
Released 1.2.1 for 1.19 on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/playlist/files/all) - you'll be able to download it once it gets approved :)

**Comment by Slips-PC** [comment]
Much Appreciated!
