### ISSUE TITLE
New set of colored icons 

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#31]
This is a more consistent version of the colored icons I will make a 3rd set later 
[consistent Playlist colored.zip](https://github.com/fudgeu/playlist/files/10551495/consistent.Playlist.colored.zip)

**Comment by DeadbushCarrot** [comment]
Hey I make a new set of colored icons and 3rd set that is a separated issue it has its zip I can just resend it here

**Comment by fudgeu** [comment]
Oh sure if you'd like! Sorry, I haven't gotten around to checking them out yet, but soon - thank you!
