### ISSUE TITLE
Game crashes when going into the end while the enderdragon is there

### ISSUE THREAD

**Issue by Kalkoen31** [fudgeu/playlist#36]
Title, consistent crashes

**Comment by Saiko125** [comment]
[crash-2023-03-09_20.02.36-client.txt](https://github.com/fudgeu/playlist/files/10935137/crash-2023-03-09_20.02.36-client.txt)


recently crashed me when going to end dimension too

sending crash report to identify issue with playlist mod

**Comment by MacchuPicchu3** [comment]
Happens to me too, sadly. I get an exit code of 255 and the following crash report:

[crash-2023-03-12_13.39.52-client.txt](https://github.com/fudgeu/playlist/files/10951702/crash-2023-03-12_13.39.52-client.txt)

**Comment by fudgeu** [comment]
Hi! This should be patched in the next update (1.3) - thank you!
