### ISSUE TITLE
Creative music in survival 

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#37]
Is it possible to make a sub option for creative music to make it play in survival in edit option menu?
and maybe the other way around?

**Comment by DeadbushCarrot** [comment]
Real quick If you make a playlist with just creative music it does play it in survival. its just if there's any type of survival music that overrides the creative music

**Comment by fudgeu** [comment]
It should be that as long as a song in your playlist doesn't have the 'Creative' category assigned to it, it should play in survival - but I'll take a look at this and confirm if it does or doesn't work once I get back from my trip :)
