### ISSUE TITLE
Minecraft crashed when clicked on "Copyright Mojang AB" button

### ISSUE THREAD

**Issue by variety754** [fudgeu/playlist#42]
https://mclo.gs/lth3MuV

**Comment by variety754** [comment]
Sometimes I got crashed when just joining the servers. It's kinda random

**Comment by fudgeu** [comment]
I *believe* another bug I fixed in the version I am currently working on may have also fixed this bug, it seems so at least. I'll do more testing when I get the chance.
For the server crashes though, that might be a separate issue, please do leave a crash log if it happens again!

**Comment by fudgeu** [comment]
1.3 is out - It was hard for me to confirm if this bug was fixed or not, so please do let me know if you still experience any of the issues!

**Comment by variety754** [comment]
Yeah, you fixed it. Thank you!
