### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by Happylama25** [fudgeu/playlist#43]
Hey!

This is a super cool mod, it works just fine on 1.19.3, however, my server has been updated to 1.19.4 and now Fabric refuses to load this mod.

It would be greatly appreciated if updated!

**Comment by fudgeu** [comment]
Yup, 1.19.4 support is coming very soon in the form of version 1.3! Should just be a couple of more days before the update is out.

**Comment by Happylama25** [comment]
Awesome! Thank you so much!

**Comment by fudgeu** [comment]
1.3 is out!
