### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#54]
Am not trying to rush you but I know someone is gunna make one of theses so yeah for future when you can!

**Comment by fudgeu** [comment]
Gonna start working on it either tonight or tomorrow - I was hoping I could create a full feature update before 1.20 came out but it came out much quicker than I expected lol

Depending on how much 1.20 requires me to change things around, hopefully I'll have something pushed out by the end of tomorrow, or the next day. After that, I'll start work on an actual feature update.

Sorry for the absence btw, I took some time off to focus on other things and a few other projects, and on top of that, moving (again) and going without internet for a while. Though, I'll likely spend some time working on a few cool things for this mod for the next while!

**Comment by DeadbushCarrot** [comment]
> Gonna start working on it either tonight or tomorrow - I was hoping I could create a full feature update before 1.20 came out but it came out much quicker than I expected lol
> 
> Depending on how much 1.20 requires me to change things around, hopefully I'll have something pushed out by the end of tomorrow, or the next day. After that, I'll start work on an actual feature update.
> 
> Sorry for the absence btw, I took some time off to focus on other things and a few other projects, and on top of that, moving (again) and going without internet for a while. Though, I'll likely spend some time working on a few cool things for this mod for the next while!
Its fine you don't always have to work on playlist I do know you were working on your website which is a very nice website btw
