### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by seventyonejump** [fudgeu/playlist#57]
I think the issue is that I love the mod. Jk it's not an issue I just wanted to say that it's the best mod I've ever seen. Idk how to say, but everything is soooo cool, every mod should be like this one!!!

Keep it up man!

**Comment by fudgeu** [comment]
Thank you so much - it means a lot!
I've taken a slight break from developing this mod, but I'm going to start working on a few updates now so hopefully you'll start seeing new stuff soon :)
