### ISSUE TITLE
[Suggestion] Add missing tracks from both alpha and beta soundtrack.

### ISSUE THREAD

**Issue by AlwaysDan007** [fudgeu/playlist#6]
Hello! I would like more songs from the Minecraft soundtrack. That is tracks like Kyoto - C418, but I am not sure if it is still in the game today.

**Comment by fudgeu** [comment]
Unfortunately, as far as I know, the missing songs aren't anywhere in the game files. I'd love to see the music in the game too - but it probably wont be able to happen sadly until I add the ability to add custom songs. Unless, I somehow strike some sort of magic legal deal with C418 to bundle the music in with my mod, but that's probably very much not going to happen, lol
