### ISSUE TITLE
Make playlist open source

### ISSUE THREAD

**Issue by JeremyStarTM** [fudgeu/playlist#60]
It would be nice if Playlist would be open source, because:
1. a GitHub repository already exists
2. more features can be added and more bugs can be squashed
3. more collaboration!
4. it would be easier to look for things in the code without decompiling the mod

Would be nice :)

**Comment by Felix14-v2** [comment]
Already suggested [here](https://github.com/fudgeu/playlist/issues/3#:~:text=I%27ll%20upload%20the%20source%20code%20pretty%20soon%2C%20likely%20when%20the%20mod%20reaches%20a%20stable%20release%20%2D%20It%27s%20my%20first%20real%20Minecraft%20mod%2C%20and%20it%20was%20definitely%20a%20learning%20process%20so%20I%20want%20to%20be%20able%20to%20clean%20up%20and%20document%20some%20of%20the%20code%20better%20before%20I%20release%20it%2C%20lol.) and [here](https://github.com/fudgeu/playlist/issues/8)

**Comment by JeremyStarTM** [comment]
Oh, didn't see them when I searched the issue tracker.

**Comment by JeremyStarTM** [comment]
Since it's a duplicate, I'll close it.
