### ISSUE TITLE
Unable to load on Quilt by default

### ISSUE THREAD

**Issue by Pete3R** [fudgeu/playlist#7]
I have tried this mod on Quilt and it has been working properly(not mentioning bugs that have just been fixed in latest release)

One issue is that whenever installing thid mos i have to jump into fabric.mod.json and change 'depends": {'
Could it be changed so that it's easier for people to use this mod on Quilt without needing to edit?

**Comment by fudgeu** [comment]
Yes, of course - I'm actually not too familiar with Quilt, but I'll take a look into it!
